Repository tektoncd/results, pull requests merged in 2020-12, with the labels that each got.

#2 Fix import paths, missing vendor files in repo move.
  cmd/api/main.go
  cmd/watcher/main.go
  config/101-mysql-deployment.yaml
  config/api.yaml
  config/watcher.yaml
  go.mod
  pkg/api/server/v1alpha1/server.go
  pkg/api/server/v1alpha1/server_test.go
  pkg/api/server/v1alpha2/result/result.go
  pkg/api/server/v1alpha2/result/result_test.go
  pkg/api/server/v1alpha2/results.go
  pkg/api/server/v1alpha2/results_test.go
  pkg/api/server/v1alpha2/server.go
  pkg/watcher/convert/convert.go
  pkg/watcher/convert/convert_test.go
  pkg/watcher/reconciler/internal/test/clients.go
  pkg/watcher/reconciler/pipelinerun/controller.go
  pkg/watcher/reconciler/pipelinerun/pipelinerun.go
  pkg/watcher/reconciler/pipelinerun/pipelinerun_test.go
  pkg/watcher/reconciler/reconciler_test.go
  pkg/watcher/reconciler/taskrun/controller.go
  pkg/watcher/reconciler/taskrun/taskrun.go
  pkg/watcher/reconciler/taskrun/taskrun_test.go
  proto/pipeline/v1beta1/common.proto
  proto/pipeline/v1beta1/pipeline_go_proto/common.pb.go
  proto/pipeline/v1beta1/pipeline_go_proto/pipelinerun.pb.go
  proto/pipeline/v1beta1/pipeline_go_proto/taskrun.pb.go
  proto/pipeline/v1beta1/pipelinerun.proto
  proto/pipeline/v1beta1/taskrun.proto
  proto/v1alpha1/api.proto
  proto/v1alpha1/internal/helpers.proto
  proto/v1alpha1/results_go_proto/api.pb.go
  proto/v1alpha1/results_go_proto/api_grpc.pb.go
  proto/v1alpha1/results_go_proto/helpers.pb.go
  proto/v1alpha2/api.proto
  proto/v1alpha2/resources.proto
  proto/v1alpha2/results_go_proto/api.pb.go
  proto/v1alpha2/results_go_proto/api_grpc.pb.go
  proto/v1alpha2/results_go_proto/resources.pb.go
  test/presubmit-tests.sh
  test/vendor/github.com/tektoncd/plumbing/LICENSE
  test/vendor/github.com/tektoncd/plumbing/scripts/README.md
  test/vendor/github.com/tektoncd/plumbing/scripts/dummy.go
  test/vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
  test/vendor/github.com/tektoncd/plumbing/scripts/library.sh
  test/vendor/github.com/tektoncd/plumbing/scripts/markdown-link-check-config.rc
  test/vendor/github.com/tektoncd/plumbing/scripts/markdown-lint-config.rc
  test/vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XXL

#4 [results] Fix lint errors.
  cmd/watcher/main.go
  go.mod
  go.sum
  pkg/api/server/v1alpha1/server.go
  pkg/api/server/v1alpha1/server_test.go
  pkg/watcher/reconciler/internal/test/clients.go
  pkg/watcher/reconciler/pipelinerun/pipelinerun.go
  pkg/watcher/reconciler/pipelinerun/pipelinerun_test.go
  pkg/watcher/reconciler/reconciler_test.go
  pkg/watcher/reconciler/taskrun/taskrun.go
  pkg/watcher/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/L

#3 [results] Implement v1alpha2 ListResults.
  pkg/api/server/cel/cel.go
  pkg/api/server/cel/cel_test.go
  pkg/api/server/db/model.go
  pkg/api/server/db/pagination/pagination.go
  pkg/api/server/db/pagination/pagination_test.go
  pkg/api/server/db/pagination/proto/generate.go
  pkg/api/server/db/pagination/proto/internal_go_proto/pagination.pb.go
  pkg/api/server/db/pagination/proto/pagination.proto
  pkg/api/server/test/db.go
  pkg/api/server/v1alpha1/server.go
  pkg/api/server/v1alpha1/server_test.go
  pkg/api/server/v1alpha2/result/result.go
  pkg/api/server/v1alpha2/result/result_test.go
  pkg/api/server/v1alpha2/results.go
  pkg/api/server/v1alpha2/results_test.go
  pkg/api/server/v1alpha2/server.go
  proto/v1alpha1/generate.go
  proto/v1alpha1/results_go_proto/api.pb.go
  proto/v1alpha1/results_go_proto/api_grpc.pb.go
Labels: approved, lgtm, size/XXL

#12 Add a link to the TEP in the main README
  README.md
Labels: approved, kind/documentation, lgtm, size/S

#10 Adds the UpdateTime field to the Result message
  go.mod
  go.sum
  pkg/api/server/db/model.go
  pkg/api/server/v1alpha2/result/result.go
  pkg/api/server/v1alpha2/result/result_test.go
  pkg/api/server/v1alpha2/results.go
  pkg/api/server/v1alpha2/results_test.go
  pkg/api/server/v1alpha2/server.go
  proto/v1alpha2/resources.proto
  proto/v1alpha2/results_go_proto/api.pb.go
  proto/v1alpha2/results_go_proto/api_grpc.pb.go
  proto/v1alpha2/results_go_proto/resources.pb.go
  schema/results.sql
Labels: approved, lgtm, size/L

#11 [v1alpha2] Add Create/GetRecord.
  go.sum
  pkg/api/server/db/errors.go
  pkg/api/server/db/model.go
  pkg/api/server/test/db.go
  pkg/api/server/v1alpha1/server.go
  pkg/api/server/v1alpha2/record/record.go
  pkg/api/server/v1alpha2/record/record_test.go
  pkg/api/server/v1alpha2/records.go
  pkg/api/server/v1alpha2/records_test.go
  pkg/api/server/v1alpha2/result/result.go
  pkg/api/server/v1alpha2/result/result_test.go
  pkg/api/server/v1alpha2/server.go
  schema/results.sql
Labels: approved, lgtm, size/XL

#16 Dynamically load DB implementation error checking.
  pkg/api/server/db/errors.go
  pkg/api/server/db/errors/errors.go
  pkg/api/server/db/errors/sqlite/sqlite.go
  pkg/api/server/test/db.go
  pkg/api/server/v1alpha2/records.go
  pkg/api/server/v1alpha2/results.go
Labels: approved, lgtm, size/L

#22 Update OWNERS.
  OWNERS
Labels: approved, lgtm, size/XS

#24 Wire up v1alpha2 API to API server.
  cmd/api/main.go
Labels: approved, lgtm, size/S

#13 Add 2021 roadmap.
  docs/roadmap.md
Labels: approved, lgtm, size/M

#20 CreateRecord: store Record data.
  pkg/api/server/internal/protoutil/protoutil.go
  pkg/api/server/v1alpha2/record/record.go
  pkg/api/server/v1alpha2/record/record_test.go
  pkg/api/server/v1alpha2/records.go
  pkg/api/server/v1alpha2/records_test.go
Labels: approved, lgtm, size/L

#19 Add a new column "annotations" to the table result
  pkg/api/server/db/model.go
  pkg/api/server/db/model_test.go
  pkg/api/server/v1alpha2/result/result.go
  pkg/api/server/v1alpha2/result/result_test.go
  pkg/api/server/v1alpha2/results.go
  pkg/api/server/v1alpha2/results_test.go
  schema/results.sql
Labels: approved, lgtm, size/L

#29 Automatically clear any proto fields marked OUTPUT_ONLY.
  pkg/api/server/internal/protoutil/protoutil.go
  pkg/api/server/internal/protoutil/protoutil_test.go
  pkg/api/server/v1alpha2/records.go
  pkg/api/server/v1alpha2/results.go
Labels: approved, lgtm, size/M

#32 Add missing license headers.
  config/100-mysql-pv.yaml
  config/101-mysql-deployment.yaml
  config/api.yaml
  config/watcher.yaml
  pkg/api/server/cel/cel.go
  pkg/api/server/cel/cel_test.go
  pkg/api/server/db/errors/errors.go
  pkg/api/server/db/errors/sqlite/sqlite.go
  pkg/api/server/db/model.go
  pkg/api/server/db/model_test.go
  pkg/api/server/db/pagination/pagination.go
  pkg/api/server/db/pagination/pagination_test.go
  pkg/api/server/db/pagination/proto/generate.go
  pkg/api/server/db/pagination/proto/pagination.proto
  pkg/api/server/internal/protoutil/protoutil.go
  pkg/api/server/internal/protoutil/protoutil_test.go
  pkg/api/server/test/db.go
  pkg/api/server/v1alpha1/server.go
  pkg/api/server/v1alpha1/server_test.go
  pkg/api/server/v1alpha2/pagination.go
  pkg/api/server/v1alpha2/pagination_test.go
  pkg/api/server/v1alpha2/record/record.go
  pkg/api/server/v1alpha2/record/record_test.go
  pkg/api/server/v1alpha2/records.go
  pkg/api/server/v1alpha2/records_test.go
  pkg/api/server/v1alpha2/result/result.go
  pkg/api/server/v1alpha2/result/result_test.go
  pkg/api/server/v1alpha2/results.go
  pkg/api/server/v1alpha2/results_test.go
  pkg/api/server/v1alpha2/server.go
  pkg/watcher/grpc/creds.go
  pkg/watcher/grpc/doc.go
  pkg/watcher/reconciler/annotation/annotation.go
  pkg/watcher/reconciler/internal/test/clients.go
  pkg/watcher/reconciler/internal/test/reconcile.go
  pkg/watcher/reconciler/pipelinerun/controller.go
  pkg/watcher/reconciler/pipelinerun/pipelinerun.go
  pkg/watcher/reconciler/pipelinerun/pipelinerun_test.go
  pkg/watcher/reconciler/reconciler_test.go
  pkg/watcher/reconciler/taskrun/controller.go
  pkg/watcher/reconciler/taskrun/taskrun.go
  pkg/watcher/reconciler/taskrun/taskrun_test.go
  proto/pipeline/v1beta1/common.proto
  proto/pipeline/v1beta1/generate.go
  proto/pipeline/v1beta1/pipelinerun.proto
  proto/pipeline/v1beta1/taskrun.proto
  proto/v1alpha1/api.proto
  proto/v1alpha1/generate.go
  proto/v1alpha1/internal/helpers.proto
  proto/v1alpha2/api.proto
  proto/v1alpha2/generate.go
  proto/v1alpha2/resources.proto
  schema/results.sql
Labels: approved, lgtm, size/XL

#30 [v1alpha2] Add UpdateRecord.
  pkg/api/server/v1alpha2/records.go
  pkg/api/server/v1alpha2/records_test.go
  proto/v1alpha2/api.proto
  proto/v1alpha2/results_go_proto/api.pb.go
Labels: approved, lgtm, size/L
