Repository tektoncd/results, pull requests merged in 2021-01, with the labels that each got.

#31 watcher/reconciler: Use controller.StartAll for integration test.
  pkg/watcher/reconciler/reconciler_test.go
Labels: approved, lgtm, size/L

#25 Implements v1alpha2 UpdateResult
  pkg/api/server/v1alpha2/results.go
  pkg/api/server/v1alpha2/results_test.go
  proto/v1alpha2/api.proto
  proto/v1alpha2/results_go_proto/api.pb.go
  proto/v1alpha2/results_go_proto/api_grpc.pb.go
  proto/v1alpha2/results_go_proto/resources.pb.go
Labels: approved, lgtm, size/XL

#37 Replace expermental language in README.
  README.md
  docs/roadmap.md
Labels: approved, lgtm, size/XS

#36 Add DEVELOPMENT.md
  DEVELOPMENT.md
  README.md
  docs/images/results.png
  proto/README.md
  test/e2e/00-setup.sh
  test/e2e/01-install.sh
  test/e2e/02-test.sh
  test/e2e/README.md
Labels: approved, lgtm, size/L

#33 Supports CreatedTime and UpdatedTime in Record.
  pkg/api/server/db/model.go
  pkg/api/server/v1alpha2/record/record.go
  pkg/api/server/v1alpha2/record/record_test.go
  pkg/api/server/v1alpha2/records.go
  pkg/api/server/v1alpha2/records_test.go
  pkg/api/server/v1alpha2/results_test.go
  pkg/api/server/v1alpha2/server_test.go
  pkg/watcher/results/results_test.go
  proto/v1alpha2/resources.proto
  proto/v1alpha2/results_go_proto/resources.pb.go
  schema/results.sql
Labels: approved, lgtm, size/L

#38 Watcher: Move PipelineRun watching to v1alpha2 API.
  cmd/watcher/main.go
  pkg/watcher/internal/test/clients.go
  pkg/watcher/internal/test/reconcile.go
  pkg/watcher/reconciler/pipelinerun/controller.go
  pkg/watcher/reconciler/pipelinerun/pipelinerun.go
  pkg/watcher/reconciler/pipelinerun/pipelinerun_test.go
  pkg/watcher/reconciler/reconciler_test.go
  pkg/watcher/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/L

#39 Remove v1alpha1 API.
  cmd/api/main.go
  docs/roadmap.md
  pkg/api/server/v1alpha1/server.go
  pkg/api/server/v1alpha1/server_test.go
  proto/v1alpha1/api.proto
  proto/v1alpha1/generate.go
  proto/v1alpha1/internal/helpers.proto
  proto/v1alpha1/results_go_proto/api.pb.go
  proto/v1alpha1/results_go_proto/api_grpc.pb.go
  proto/v1alpha1/results_go_proto/helpers.pb.go
Labels: approved, lgtm, size/XXL

#35 Implements the v1alpha2 ETAG
  pkg/api/server/db/model.go
  pkg/api/server/v1alpha2/record/record.go
  pkg/api/server/v1alpha2/record/record_test.go
  pkg/api/server/v1alpha2/records.go
  pkg/api/server/v1alpha2/records_test.go
  pkg/api/server/v1alpha2/result/result.go
  pkg/api/server/v1alpha2/result/result_test.go
  pkg/api/server/v1alpha2/results.go
  pkg/api/server/v1alpha2/results_test.go
  pkg/watcher/results/results_test.go
  schema/results.sql
Labels: approved, lgtm, size/L

#43 Watcher: Automatically group records with known parent types.
  docs/watcher/README.md
  pkg/watcher/reconciler/pipelinerun/pipelinerun_test.go
  pkg/watcher/reconciler/reconciler_test.go
  pkg/watcher/reconciler/taskrun/taskrun_test.go
  pkg/watcher/results/results.go
  pkg/watcher/results/results_test.go
Labels: approved, lgtm, size/L

#46 API: Allow uppercase letters in names.
  pkg/api/server/v1alpha2/record/record.go
  pkg/api/server/v1alpha2/record/record_test.go
  pkg/api/server/v1alpha2/result/result.go
  pkg/api/server/v1alpha2/result/result_test.go
Labels: approved, lgtm, size/M

#44 Add docs for using grpc_cli for manual debugging.
  DEVELOPMENT.md
Labels: approved, lgtm, size/M

#49 Revert "API: Allow uppercase letters in names."
  pkg/api/server/v1alpha2/record/record.go
  pkg/api/server/v1alpha2/record/record_test.go
  pkg/api/server/v1alpha2/result/result.go
  pkg/api/server/v1alpha2/result/result_test.go
Labels: approved, lgtm, size/M

#47 Watcher: Add flag for disabling annotation updates.
  cmd/watcher/main.go
  pkg/watcher/reconciler/config.go
  pkg/watcher/reconciler/config_test.go
  pkg/watcher/reconciler/pipelinerun/controller.go
  pkg/watcher/reconciler/pipelinerun/pipelinerun.go
  pkg/watcher/reconciler/pipelinerun/pipelinerun_test.go
  pkg/watcher/reconciler/reconciler_test.go
  pkg/watcher/reconciler/taskrun/controller.go
  pkg/watcher/reconciler/taskrun/taskrun.go
  pkg/watcher/reconciler/taskrun/taskrun_test.go
  pkg/watcher/results/results.go
  pkg/watcher/results/results_test.go
Labels: approved, lgtm, size/L

#51 Implements DeleteRecord
  pkg/api/server/v1alpha2/records.go
  pkg/api/server/v1alpha2/records_test.go
  pkg/api/server/v1alpha2/results_test.go
Labels: approved, lgtm, size/M

#54 Adds test case for cascade delete.
  pkg/api/server/v1alpha2/results_test.go
Labels: approved, lgtm, size/M

#57 Add health checking endpoints to RPC server.
  cmd/api/main.go
Labels: approved, lgtm, size/XS

#56 API: Allow users to list records across results.
  docs/api/README.md
  go.mod
  go.sum
  pkg/api/server/v1alpha2/records.go
  pkg/api/server/v1alpha2/records_test.go
Labels: approved, lgtm, size/L

#55 Add Tekton CI/Release configs.
  .yamllint
  tekton/ci-run.yaml
  tekton/ci.yaml
  tekton/release-api.yaml
  tekton/release-watcher.yaml
  tekton/release.yaml
  tekton/tasks/ko/ko.yaml
  tekton/vendor/README.md
  tekton/vendor/vendor.sh
Labels: approved, lgtm, size/L

#63 Add installation docs, move mysql-init to config/.
  config/100-mysql-init.yaml
  config/generate.go
  docs/install.md
  test/e2e/01-install.sh
Labels: approved, lgtm, size/M

#62 API: add complex query to cookbook.
  docs/api/README.md
Labels: approved, lgtm, size/XS

#61 Separate result configs from pipelines.
  config/100-api-serviceaccount.yaml
  config/100-watcher-serviceaccount.yaml
  config/200-mysql-pv.yaml
  config/201-mysql-deployment.yaml
  config/api.yaml
  config/watcher.yaml
Labels: approved, lgtm, size/M

#64 Add release script.
  release/release.sh
Labels: approved, lgtm, size/S

#67 Add godoc, Go Report Card README badges.
  README.md
Labels: approved, lgtm, size/XS

#60 API: Add support for RBAC Auth.
  config/100-api-serviceaccount.yaml
  config/100-watcher-serviceaccount.yaml
  pkg/api/server/v1alpha2/auth/auth.go
  pkg/api/server/v1alpha2/auth/nop.go
  pkg/api/server/v1alpha2/auth/rbac.go
  pkg/api/server/v1alpha2/auth/rbac_test.go
  pkg/api/server/v1alpha2/records.go
  pkg/api/server/v1alpha2/records_test.go
  pkg/api/server/v1alpha2/results.go
  pkg/api/server/v1alpha2/server.go
  pkg/internal/test/clients.go
  pkg/watcher/reconciler/pipelinerun/pipelinerun_test.go
  pkg/watcher/reconciler/reconciler_test.go
  pkg/watcher/reconciler/taskrun/taskrun_test.go
  pkg/watcher/results/results_test.go
Labels: approved, lgtm, size/L

#66 Use standard StorageClass for MySQL pvc.
  config/200-mysql-pv.yaml
Labels: approved, lgtm, size/S

#69 Move top level README to docs.
  docs/DEVELOPMENT.md
  docs/README.md
Labels: approved, lgtm, size/S
