Repository tektoncd/results, pull requests merged in 2021-02, with the labels that each got.

#75 Update roadmap post-v0.1.0 release with completed tasks.
  docs/roadmap.md
Labels: approved, lgtm, size/S

#72 Add simple UI for visualizing Result data.
  go.mod
  go.sum
  tools/simpleui/README.md
  tools/simpleui/main.go
  tools/simpleui/template.go
  tools/simpleui/templates/records.html
  tools/simpleui/templates/results.html
Labels: approved, lgtm, size/L

#77 [watcher] Use MergePatch type instead of JSON Patch.
  go.mod
  pkg/watcher/reconciler/annotation/annotation.go
  pkg/watcher/reconciler/pipelinerun/pipelinerun.go
  pkg/watcher/reconciler/taskrun/taskrun.go
  test/e2e/02-test.sh
Labels: approved, lgtm, size/M

#78 Enable TLS and use Service Account tokens in Watcher.
  cmd/api/main.go
  cmd/watcher/main.go
  config/api.yaml
  config/default-clusterroles.yaml
  config/watcher.yaml
  docs/DEVELOPMENT.md
  docs/api/README.md
  docs/install.md
  go.mod
  pkg/api/server/v1alpha2/auth/rbac.go
  pkg/api/server/v1alpha2/auth/rbac_test.go
  test/e2e/00-setup.sh
  test/e2e/01-install.sh
Labels: approved, lgtm, size/L

#79 Update installation docs with instructions for installing from release.
  docs/README.md
  docs/install.md
  docs/roadmap.md
Labels: approved, lgtm, size/M

#84 Update README.
  docs/README.md
  docs/images/datamodel.png
  docs/images/overview.png
  docs/install.md
Labels: approved, lgtm, size/M

#88 Add background to datamodel image
  docs/images/datamodel.png
Labels: approved, lgtm, size/XS

#86 Add hugo frontmatter labels to README.md.
  docs/README.md
Labels: approved, lgtm, size/S

#90 Fix typo in README.md frontmatter.
  docs/README.md
Labels: approved, lgtm, size/XS

#91 Add frontmatter for api and watcher docs.
  docs/api/README.md
  docs/watcher/README.md
Labels: approved, lgtm, size/S

#92 e2e tests: Rewrite e2e tests in Go.
  go.mod
  test/e2e/02-test.sh
  test/e2e/README.md
  test/e2e/e2e_test.go
Labels: approved, lgtm, size/L
