Repository tektoncd/results, pull requests merged in 2021-03, with the labels that each got.

#95 Add Subject Alternative Name to test certificate script
  docs/install.md
  test/e2e/01-install.sh
Labels: approved, lgtm, size/XS

#96 Add certificate generation for legacy openssl versions (e.g. MacOS Big Sur)
  test/e2e/01-install.sh
Labels: approved, lgtm, size/M

#89 Update Cookbook with failed run and duration queries.
  docs/README.md
  docs/api/README.md
Labels: approved, lgtm, size/S

#98 Document applying all with kustomize and use `kubectl kustomize` instead
  docs/DEVELOPMENT.md
  test/e2e/01-install.sh
Labels: approved, lgtm, size/S

#87 Add order_by to results and records
  docs/DEVELOPMENT.md
  docs/api/README.md
  pkg/api/server/v1alpha2/ordering.go
  pkg/api/server/v1alpha2/ordering_test.go
  pkg/api/server/v1alpha2/records.go
  pkg/api/server/v1alpha2/records_test.go
  pkg/api/server/v1alpha2/results.go
  pkg/api/server/v1alpha2/results_test.go
  proto/v1alpha2/api.proto
  proto/v1alpha2/results_go_proto/api.pb.go
  proto/v1alpha2/results_go_proto/api_grpc.pb.go
  proto/v1alpha2/results_go_proto/resources.pb.go
Labels: approved, lgtm, size/XL

#94 simpleui: Add query, parent fields.
  tools/simpleui/main.go
  tools/simpleui/template.go
  tools/simpleui/templates/records.html
Labels: approved, lgtm, size/M
