Repository tektoncd/results, pull requests merged in 2022-03, with the labels that each got.

#165 watcher: Add back missing reconciler config values.
  pkg/watcher/reconciler/pipelinerun/controller.go
  pkg/watcher/reconciler/taskrun/controller.go
Labels: size/XS, lgtm, approved

#163 Add Uber/Automaxprocs to autoset GOMAXPROCS to CPU quota
  cmd/api/main.go
  go.mod
Labels: size/XS, kind/misc, lgtm, approved

#167 Add results-info ConfigMap and supporting roles
  config/config-info.yaml
  config/kustomization.yaml
  release/release.sh
Labels: size/M, lgtm, approved
