Repository tektoncd/results, pull requests merged in 2022-12, with the labels that each got.

#268 Hide sensitive information from pod logs.
  cmd/api/README.md
  cmd/api/main.go
  docs/DEVELOPMENT.md
  pkg/watcher/reconciler/dynamic/dynamic.go
Labels: ok-to-test, size/M, lgtm, approved

#275 Audit Logging
  cmd/api/main.go
  go.mod
  go.sum
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/.gitignore
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/.travis.yml
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/CHANGELOG.md
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/CONTRIBUTING.md
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/LICENSE
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/README.md
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/auth/auth.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/auth/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/auth/metadata.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/logging/common.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/logging/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/logging/settable/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/logging/settable/logsettable.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/logging/zap/client_interceptors.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/logging/zap/context.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/logging/zap/ctxzap/context.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/logging/zap/ctxzap/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/logging/zap/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/logging/zap/grpclogger.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/logging/zap/options.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/logging/zap/payload_interceptors.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/logging/zap/server_interceptors.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/makefile
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/slack.png
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/tags/context.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/tags/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/tags/fieldextractor.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/tags/interceptors.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/tags/options.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/util/metautils/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/util/metautils/nicemd.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/wrappers.go
  vendor/modules.txt
Labels: ok-to-test, size/XXL, lgtm, approved

#274 Fix api config location and e2e tests
  cmd/api/main.go
  config/api.yaml
  test/e2e/00-setup.sh
  test/e2e/01-install.sh
  test/e2e/e2e.sh
Labels: size/S, ok-to-test, lgtm, approved

#283 Make sa token and certificates path configurable.
  test/e2e/01-install.sh
  test/e2e/e2e.sh
  test/e2e/e2e_test.go
  test/e2e/grpc_client.go
Labels: ok-to-test, size/M, lgtm, approved

#285 [Optional pr] Add log level value to the api server config.
  config/env/config
Labels: size/XS, ok-to-test, lgtm, approved
