Repository tektoncd/results, pull requests merged in 2022-09, with the labels that each got.

#226 Add adambkaplan and vdemeester as Results owners
  OWNERS
Labels: size/XS, lgtm, approved

#232 Read the parent name from the results annotation when it's set
  pkg/watcher/results/results.go
  pkg/watcher/results/results_test.go
Labels: ok-to-test, size/M, lgtm, approved

#200 Added REST proxy over existing RPCs
  .gitignore
  cmd/api/README.md
  cmd/api/main.go
  config/api.yaml
  env/config
  go.mod
  go.sum
  proto/v1alpha2/generate.go
  proto/v1alpha2/results_go_proto/api.pb.go
  proto/v1alpha2/results_go_proto/api.pb.gw.go
  proto/v1alpha2/results_go_proto/api_grpc.pb.go
  proto/v1alpha2/results_go_proto/resources.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/LICENSE.txt
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/internal/httprule/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/internal/httprule/compile.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/internal/httprule/fuzz.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/internal/httprule/parse.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/internal/httprule/types.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/convert.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/doc.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/fieldmask.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/marshal_httpbodyproto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/marshal_json.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/marshal_jsonpb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/marshal_proto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/marshaler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/marshaler_registry.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/pattern.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/proto2_convert.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/query.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/doc.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/pattern.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/readerfactory.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/string_array_flag.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/trie.go
  vendor/modules.txt
Labels: ok-to-test, size/XXL, lgtm, approved

#236 Delete release.yaml
  release.yaml
Labels: size/L, lgtm, approved

#244 Fix the API server startup
  cmd/api/README.md
  cmd/api/main.go
  config/api.yaml
  config/env/config
  config/kustomization.yaml
Labels: size/S, ok-to-test, lgtm, approved
