Repository tektoncd/results, pull requests merged in 2022-02, with the labels that each got.

#159 DEVELOPMENT.md: Fix kubectl link
  docs/DEVELOPMENT.md
Labels: size/XS, lgtm, approved

#160 e2e: Update client-go calls to use ctx based signatures.
  test/e2e/README.md
  test/e2e/e2e_test.go
Labels: size/S, lgtm, approved

#153 configure postgres to use the volume mount for data persistence
  config/201-sql-deployment.yaml
Labels: size/XS, ok-to-test, lgtm, approved

#157 Refactor reconcilers to use Object interfaces.
  pkg/watcher/reconciler/dynamic/clients.go
  pkg/watcher/reconciler/dynamic/controller.go
  pkg/watcher/reconciler/dynamic/dynamic.go
  pkg/watcher/reconciler/dynamic/dynamic_test.go
  pkg/watcher/reconciler/pipelinerun/controller.go
  pkg/watcher/reconciler/pipelinerun/reconciler.go
  pkg/watcher/reconciler/reconciler_test.go
  pkg/watcher/reconciler/taskrun/controller.go
  pkg/watcher/reconciler/taskrun/reconciler.go
  pkg/watcher/results/results.go
Labels: size/XL, lgtm, approved
