Repository tektoncd/results, pull requests merged in 2022-08, with the labels that each got.

#213 Remove wlynch from active reviewers.
  OWNERS
Labels: size/XS, lgtm, approved

#193 Fix Postgres permission issue
  config/201-sql-deployment.yaml
Labels: size/XS, lgtm, approved

#212 fix broken link Any.type
  docs/api/README.md
Labels: size/XS, ok-to-test, lgtm, approved

#214 Allow configuration of API server through config file
  cmd/api/README.md
  cmd/api/main.go
  env/config
  go.mod
  go.sum
Labels: ok-to-test, size/M, lgtm, approved
