Repository tektoncd/results, pull requests merged in 2023-11, with the labels that each got.

#663 Drop NET_BIND_SERVICE cap as it isn't necessary
  config/base/api.yaml
  config/base/watcher.yaml
Labels: size/XS, ok-to-test, release-note, kind/cleanup, lgtm, approved

#666 Fix log forwarding for PipelineRun status Completed
  pkg/watcher/reconciler/dynamic/dynamic.go
Labels: kind/bug, size/XS, release-note-none, lgtm, approved

#661 Use best practices for namespaces in kustomization
  config/base/100-api-serviceaccount.yaml
  config/base/100-watcher-serviceaccount.yaml
  config/base/api.yaml
  config/base/config-info.yaml
  config/base/config-leader-election.yaml
  config/base/config-logging.yaml
  config/base/config-observability.yaml
  config/base/kustomization.yaml
  config/base/watcher.yaml
  config/components/local-db/201-sql-deployment.yaml
  config/components/local-db/api.yaml
  config/components/local-db/kustomization.yaml
  config/components/logs-file/api.yaml
  config/components/logs-file/kustomization.yaml
  config/components/logs-file/pvc.yaml
  config/overlays/base-only/kustomization.yaml
  config/overlays/default-local-db/kustomization.yaml
  config/overlays/logs-local-db/kustomization.yaml
  release/kustomization.yaml
  test/e2e/kustomize/kustomization.yaml
Labels: release-note-none, ok-to-test, size/M, kind/cleanup, lgtm, approved

#658 Add support for database SSL verification and encryption
  cmd/api/README.md
  cmd/api/main.go
  config/base/env/config
  docs/database-ssl-mode-custom-CA-cert.md
  pkg/api/server/config/config.go
Labels: kind/feature, release-note, size/M, lgtm, approved

#662 Use enviornment variables for watcher cli args
  config/base/watcher.yaml
Labels: size/S, ok-to-test, release-note, kind/cleanup, lgtm, approved

#672 Add owner references check optional in watcher
  cmd/watcher/main.go
  docs/watcher/README.md
  pkg/watcher/reconciler/config.go
  pkg/watcher/reconciler/dynamic/dynamic.go
  pkg/watcher/reconciler/dynamic/dynamic_test.go
Labels: kind/feature, release-note, size/M, lgtm, approved
