Repository tektoncd/results, pull requests merged in 2023-10, with the labels that each got.

#625 Make sure gRPC connection is closed
  pkg/watcher/reconciler/dynamic/dynamic.go
Labels: size/XS, release-note-none, ok-to-test, lgtm, approved

#626 improve watcher logs
  pkg/watcher/reconciler/dynamic/dynamic.go
  pkg/watcher/reconciler/pipelinerun/reconciler.go
  pkg/watcher/reconciler/taskrun/reconciler.go
Labels: ok-to-test, release-note, size/M, kind/cleanup, lgtm, approved

#635 Fix SAR groups and Extra
  pkg/api/server/v1alpha2/auth/rbac.go
  pkg/api/server/v1alpha2/auth/rbac_test.go
Labels: kind/bug, release-note, size/M, lgtm, approved

#643 [v0.8.x] Bump GRPC Go to v1.57.2
  go.mod
  go.sum
  tools/tkn-results/go.mod
  tools/tkn-results/go.sum
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: release-note, size/M, lgtm, approved, kind/security

#653 Fix documentation typo
  docs/external-database.md
Labels: size/XS, release-note-none, kind/cleanup, lgtm, approved

#654 Update PostgreSQL image used in local-db deployment
  config/components/local-db/201-sql-deployment.yaml
Labels: size/XS, release-note-none, kind/misc, lgtm, approved

#627 fix subgrouping not working in CEL filters
  pkg/api/server/cel2sql/convert_test.go
  pkg/api/server/cel2sql/interpreter.go
  pkg/api/server/cel2sql/operators.go
  pkg/api/server/v1alpha2/lister/filter_test.go
  pkg/api/server/v1alpha2/lister/lister_test.go
Labels: kind/bug, ok-to-test, release-note, size/M, lgtm, approved

#632 Feature: Rest log streaming
  docs/api/openapi.yaml
  docs/api/rest-api-spec.md
  docs/large-log-files.md
  pkg/api/server/v1alpha2/logs.go
  pkg/api/server/v1alpha2/logs_test.go
  pkg/logs/writer.go
  pkg/logs/writer_test.go
  proto/v1alpha2/api.proto
  proto/v1alpha2/results_go_proto/api.pb.go
  proto/v1alpha2/results_go_proto/api_grpc.pb.go
  proto/v1alpha2/results_go_proto/resources.pb.go
Labels: kind/feature, release-note-action-required, size/XL, lgtm, approved
