Repository tektoncd/results, pull requests merged in 2023-09, with the labels that each got.

#575 [CLI] Support passing of Service Account to tkn-results
  tools/tkn-results/cmd/root.go
  tools/tkn-results/docs/tkn-results.md
  tools/tkn-results/docs/tkn-results_list.md
  tools/tkn-results/docs/tkn-results_records.md
  tools/tkn-results/docs/tkn-results_records_list.md
  tools/tkn-results/internal/client/client.go
  tools/tkn-results/internal/config/config.go
Labels: kind/feature, release-note, size/M, lgtm, approved

#566 update CEL filtering documentation
  docs/api/README.md
Labels: release-note-none, kind/documentation, size/XL, lgtm, approved

#588 add instructions for handling large log files
  docs/large-log-files.md
Labels: release-note-none, size/L, ok-to-test, kind/documentation, lgtm, approved

#604 config file not present should be handled
  tools/tkn-results/internal/config/config.go
Labels: kind/bug, size/XS, ok-to-test, release-note, lgtm, approved

#596 Fix release script GCS bucket for the release.yaml
  tekton/release.yaml
Labels: size/XS, release-note-none, kind/misc, lgtm, approved

#441 Add Release Cheatsheet for Results
  tekton/release-cheatsheet.md
Labels: release-note-none, size/L, kind/documentation, lgtm, approved

#618 Fix flag passing when config file isn't present
  tools/tkn-results/internal/config/config.go
Labels: kind/bug, size/XS, release-note-none, lgtm, approved
