Repository tektoncd/results, pull requests merged in 2023-06, with the labels that each got.

#491 Fix watcher log level description in documentation
  config/base/100-watcher-serviceaccount.yaml
  docs/DEVELOPMENT.md
Labels: size/XS, ok-to-test, release-note, kind/documentation, lgtm, approved

#479 Fix Image Repo for Release Pipeline
  tekton/release.yaml
Labels: size/XS, release-note-none, kind/misc, lgtm, approved

#326 Install: add option for localhost DNS name
  test/e2e/01-install.sh
  test/e2e/README.md
Labels: size/S, release-note-none, kind/documentation, kind/misc, lgtm, approved

#508 Temporary freeze tekton pipelines version for e2e test.
  test/e2e/01-install.sh
Labels: size/XS, ok-to-test, release-note, lgtm, approved

#505 Add recovery middleware to gRPC server
  cmd/api/main.go
  go.mod
  go.sum
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/COPYRIGHT
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/LICENSE
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/recovery/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/recovery/interceptors.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/recovery/options.go
  vendor/modules.txt
Labels: size/L, release-note, kind/misc, lgtm, approved

#511 Add option to enable prometheus histogram
  cmd/api/README.md
  cmd/api/main.go
  config/base/env/config
  pkg/api/server/config/config.go
Labels: kind/feature, size/XS, release-note, kind/misc, lgtm, approved
