Repository tektoncd/results, pull requests merged in 2023-01, with the labels that each got.

#302 Enable REST endpoints if logging is on
  cmd/api/main.go
Labels: size/XS, ok-to-test, lgtm, approved

#320 Add myself to the OWNERS file
  OWNERS
Labels: size/XS, lgtm, approved

#315 Fix DEVELOPMENT documentation
  docs/DEVELOPMENT.md
  docs/api/README.md
Labels: size/S, ok-to-test, lgtm, approved

#316 Remove watcher reconciler unittest
  pkg/watcher/reconciler/reconciler_test.go
Labels: size/L, ok-to-test, lgtm, approved

#298 Fix insertion of child resources
  pkg/watcher/results/results.go
  pkg/watcher/results/results_test.go
Labels: size/L, lgtm, approved

#317 Change the ClusterRoles for Logging
  config/default-clusterroles.yaml
Labels: size/XS, lgtm, approved

#319 API fix for REST access
  proto/v1alpha2/api.proto
  proto/v1alpha2/resources.proto
  proto/v1alpha2/results_go_proto/api.pb.go
  proto/v1alpha2/results_go_proto/api.pb.gw.go
  proto/v1alpha2/results_go_proto/api_grpc.pb.go
  proto/v1alpha2/results_go_proto/resources.pb.go
Labels: ok-to-test, size/XL, lgtm, approved

#294 Fix isDone function, improve visibility as well as traceability and skip deleted keys
  pkg/watcher/reconciler/dynamic/dynamic.go
  pkg/watcher/reconciler/dynamic/dynamic_test.go
  pkg/watcher/reconciler/pipelinerun/reconciler.go
  pkg/watcher/reconciler/taskrun/reconciler.go
Labels: size/L, lgtm, approved
