Repository tektoncd/results, pull requests merged in 2023-08, with the labels that each got.

#563 Fix status 404 for LIST records
  pkg/api/server/v1alpha2/records.go
  pkg/api/server/v1alpha2/records_test.go
Labels: kind/bug, size/S, release-note-action-required, lgtm, approved

#520 feat(cli): tkn-result would port-forward to service/tekton-results-api-service automatically
  go.sum
  tools/tkn-results/cmd/help.txt
  tools/tkn-results/cmd/root.go
  tools/tkn-results/docs/tkn-results.md
  tools/tkn-results/go.sum
  tools/tkn-results/internal/client/client.go
  tools/tkn-results/internal/config/config.go
  tools/tkn-results/internal/flags/flags.go
  tools/tkn-results/internal/portforward/portforward.go
  tools/tkn-results/main.go
Labels: kind/feature, size/L, ok-to-test, release-note, lgtm, approved

#536 Remove TLS hostname override
  cmd/api/README.md
  cmd/api/main.go
  config/base/env/config
  pkg/api/server/config/config.go
  test/e2e/kustomize/api-server.yaml
  test/e2e/kustomize/kustomization.yaml
Labels: kind/bug, release-note-action-required, size/M, lgtm, approved

#461 [CLI] Fix the global flag passing from cli arg
  tools/tkn-results/internal/config/config.go
Labels: kind/bug, size/XS, release-note-none, lgtm, approved, lifecycle/stale

#457 [CLI] Add integration support to tkn
  tools/tkn-results/cmd/list.go
  tools/tkn-results/cmd/records/list.go
  tools/tkn-results/cmd/records/records.go
  tools/tkn-results/cmd/root.go
Labels: kind/feature, size/S, release-note, lgtm, approved

#568 [CLI] Fix the broken flags
  tools/tkn-results/cmd/root.go
  tools/tkn-results/go.mod
  tools/tkn-results/go.sum
  tools/tkn-results/internal/client/client.go
  tools/tkn-results/internal/config/config.go
  tools/tkn-results/internal/config/config_test.go
Labels: kind/bug, release-note-none, size/M, lgtm, approved

#487 Add ClusterRole aggregation for default user-facing roles
  config/base/default-clusterroles.yaml
Labels: kind/bug, size/XS, release-note-none, lgtm, approved

#454 Bump k8s version used by Kind and e2e tests
  test/e2e/kind-cluster.yaml
Labels: size/XS, release-note-none, kind/misc, lgtm, approved

#541 add installing results with external database docs
  docs/external-database.md
  docs/install.md
Labels: release-note-none, size/L, ok-to-test, kind/documentation, lgtm, approved

#555 add myself as a reviewer
  OWNERS
Labels: size/XS, release-note-none, ok-to-test, kind/misc, lgtm, approved

#583 [CLI] Fix empty value for commandline flag
  tools/tkn-results/cmd/root.go
  tools/tkn-results/internal/config/config.go
  tools/tkn-results/internal/config/config_test.go
Labels: kind/bug, size/S, release-note-none, lgtm, approved

#577 [CLI] Add insecure flag to make insecure GRPC TLS call
  tools/tkn-results/cmd/root.go
  tools/tkn-results/docs/tkn-results.md
  tools/tkn-results/docs/tkn-results_list.md
  tools/tkn-results/docs/tkn-results_records.md
  tools/tkn-results/docs/tkn-results_records_list.md
  tools/tkn-results/internal/client/client.go
  tools/tkn-results/internal/config/config.go
Labels: kind/feature, release-note, size/M, lgtm, approved
