Repository tektoncd/results, pull requests merged in 2023-03, with the labels that each got.

#367 Fix log streaming error.
  config/base/100-watcher-serviceaccount.yaml
Labels: kind/bug, size/XS, release-note-none, ok-to-test, lgtm, approved

#384 Remove ppc64le and s390x release unittest
  tekton/release.yaml
Labels: release-note-none, kind/misc, size/M, lgtm, approved

#385 Add Arm64 and Arm arch support
  release/release.sh
  tekton/ci.yaml
Labels: release-note-none, kind/misc, size/M, lgtm, approved

#380 Fix the command for redeploying all components
  docs/DEVELOPMENT.md
Labels: size/XS, release-note, kind/documentation, lgtm, approved

#387 Add release config to bucket's latest folder
  tekton/release.yaml
Labels: size/XS, release-note-none, kind/misc, lgtm, approved

#376 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: release-note-none, kind/misc, size/M, lgtm, approved

#386 dependabot: do not update k8s.io/* major/minor updates
  .github/dependabot.yml
Labels: size/XS, release-note-none, kind/misc, lgtm, approved

#333 Wait until all TaskRuns are ready for deletion to delete the PipelineRun
  pkg/watcher/reconciler/annotation/annotation.go
  pkg/watcher/reconciler/annotation/annotation_test.go
  pkg/watcher/reconciler/dynamic/dynamic.go
  pkg/watcher/reconciler/dynamic/dynamic_test.go
  pkg/watcher/reconciler/pipelinerun/controller.go
  pkg/watcher/reconciler/pipelinerun/reconciler.go
  pkg/watcher/reconciler/pipelinerun/reconciler_test.go
  test/e2e/e2e_test.go
Labels: kind/bug, release-note, size/XL, lgtm, approved

#394 Update install latest release to 0.5.0
  docs/install.md
Labels: size/XS, release-note-none, ok-to-test, kind/documentation, kind/misc, lgtm, approved

#346 Fix: Error message for GetResult handler
  pkg/api/server/v1alpha2/results.go
Labels: kind/bug, size/XS, release-note, lgtm, approved

#421 Fix: API Server panics when bearer token with invalid JWT format is passed
  cmd/api/main.go
  cmd/api/main_test.go
Labels: kind/bug, release-note, size/M, lgtm, approved

#373 Feature: Add impersonation to tekton results API
  cmd/api/README.md
  cmd/api/main.go
  config/base/env/config
  docs/api/README.md
  go.mod
  go.sum
  pkg/api/server/config/config.go
  pkg/api/server/v1alpha2/auth/impersonation/impersonation.go
  pkg/api/server/v1alpha2/auth/impersonation/impersonation_test.go
  pkg/api/server/v1alpha2/auth/rbac.go
  pkg/api/server/v1alpha2/auth/rbac_test.go
  vendor/k8s.io/apiserver/LICENSE
  vendor/k8s.io/apiserver/pkg/authentication/serviceaccount/util.go
  vendor/k8s.io/apiserver/pkg/authentication/user/doc.go
  vendor/k8s.io/apiserver/pkg/authentication/user/user.go
  vendor/modules.txt
Labels: kind/feature, size/XXL, release-note-action-required, lgtm, approved
