Repository tektoncd/results, pull requests merged in 2024-03, with the labels that each got.

#702 fix: prevent panic when a record Summary is not a valid object
  pkg/watcher/results/results.go
Labels: kind/bug, size/XS, release-note-none, ok-to-test, lgtm, approved

#722 Support all data types in summary annotations
  pkg/watcher/results/results.go
  pkg/watcher/results/results_test.go
Labels: kind/bug, size/S, release-note, lgtm, approved

#727 Disable Proxy for Rest to GRPC communication
  cmd/api/main.go
Labels: kind/bug, size/XS, release-note-none, lgtm, approved

#740 Don't run auth check for every log fragment
  pkg/api/server/v1alpha2/logs.go
Labels: size/S, release-note-none, ok-to-test, lgtm, approved
