Repository tektoncd/results, pull requests merged in 2024-01, with the labels that each got.

#690 Fix deletion when TaskRun is part of PipelineRun
  pkg/watcher/reconciler/dynamic/dynamic.go
  pkg/watcher/reconciler/dynamic/dynamic_test.go
Labels: kind/bug, release-note, size/M, lgtm, approved

#679 updated deprecated field in docs
  docs/api/README.md
Labels: size/S, release-note-none, ok-to-test, kind/documentation, lgtm, approved

#642 Implementation of Summary/Aggregation API in Tekton results
  config/base/default-clusterroles.yaml
  docs/api/summary-api.md
  pkg/api/server/v1alpha2/auth/auth.go
  pkg/api/server/v1alpha2/lister/aggregator.go
  pkg/api/server/v1alpha2/lister/aggregator_test.go
  pkg/api/server/v1alpha2/summary.go
  proto/v1alpha2/api.proto
  proto/v1alpha2/resources.proto
  proto/v1alpha2/results_go_proto/api.pb.go
  proto/v1alpha2/results_go_proto/api.pb.gw.go
  proto/v1alpha2/results_go_proto/api_grpc.pb.go
  proto/v1alpha2/results_go_proto/resources.pb.go
Labels: size/XXL, release-note, lgtm, approved

#608 Remove Config Values as Env var in API server
  config/base/api.yaml
  config/base/env/config
  config/components/local-db/api.yaml
  config/components/local-db/kustomization.yaml
  test/e2e/gcs-emulator.yaml
Labels: kind/bug, release-note, size/M, lgtm, approved
