Repository tektoncd/results, pull requests merged in 2024-12, with the labels that each got.

#896 Fix the blob for s3 prefixed key
  pkg/api/server/v1alpha2/plugin/plugin_logs.go
Labels: kind/bug, release-note, size/M, lgtm, approved

#901 Fix the Unauthorized for the Rest API
  pkg/api/server/v1alpha2/plugin/plugin_logs.go
Labels: kind/bug, size/XS, release-note, lgtm, approved

#905 Enable Impersonation of user in Rest API for Logging
  pkg/api/server/v1alpha2/plugin/plugin_logs.go
Labels: kind/feature, size/XS, release-note-none, lgtm, approved

#910 fix: log file setup
  config/components/logs-file/kustomization.yaml
  config/components/logs-file/watcher.yaml
Labels: size/S, ok-to-test, release-note, lgtm, approved
