Repository tektoncd/results, pull requests merged in 2024-11, with the labels that each got.

#870 Fix Panic in the API server
  pkg/api/server/v1alpha2/plugin_logs.go
Labels: kind/bug, size/XS, release-note, lgtm, approved

#789 Add watcher option logs_timestamps to store taskrun logs with timestamps
  cmd/api/README.md
  cmd/watcher/main.go
  config/base/env/config
  pkg/api/server/config/config.go
  pkg/watcher/reconciler/config.go
  pkg/watcher/reconciler/dynamic/dynamic.go
Labels: kind/feature, size/XS, ok-to-test, release-note, lgtm, approved

#868 Remove GRPC Proxy for v3 Log Rest API Call
  cmd/api/main.go
  pkg/api/server/v1alpha2/handlers.go
  pkg/api/server/v1alpha2/plugin_logs.go
  proto/v1alpha3/log.proto
  proto/v1alpha3/results_go_proto/log.pb.go
  proto/v1alpha3/results_go_proto/log.pb.gw.go
Labels: kind/feature, size/L, release-note, lgtm, approved

#880 Provide configurations to store labels and Annotations in summary
  cmd/watcher/main.go
  pkg/watcher/reconciler/config.go
  pkg/watcher/reconciler/dynamic/dynamic.go
  pkg/watcher/results/results.go
  pkg/watcher/results/results_test.go
  test/e2e/e2e_test.go
Labels: kind/feature, release-note, size/M, lgtm, approved

#888 Enable Finalizer for Pruner - Grace Period Config
  pkg/watcher/reconciler/dynamic/dynamic.go
  pkg/watcher/reconciler/pipelinerun/reconciler.go
  pkg/watcher/reconciler/taskrun/reconciler.go
  test/e2e/kustomize/watcher.yaml
Labels: kind/feature, size/S, release-note, lgtm, approved
