Repository tektoncd/results, pull requests merged in 2024-07, with the labels that each got.

#766 Use latest Kind k8s version, fixes e2e tests
  test/e2e/kind-cluster.yaml
Labels: size/XS, release-note, lgtm, approved

#748 Enable storing of Run Events as Record
  cmd/watcher/main.go
  config/base/100-watcher-serviceaccount.yaml
  docs/api/README.md
  pkg/apis/v1alpha3/types.go
  pkg/watcher/reconciler/annotation/annotation.go
  pkg/watcher/reconciler/config.go
  pkg/watcher/reconciler/dynamic/dynamic.go
  pkg/watcher/reconciler/dynamic/dynamic_test.go
  pkg/watcher/reconciler/pipelinerun/controller.go
  pkg/watcher/reconciler/pipelinerun/reconciler.go
  pkg/watcher/reconciler/taskrun/controller.go
  pkg/watcher/reconciler/taskrun/reconciler.go
  pkg/watcher/results/eventlist.go
  test/e2e/e2e_test.go
  test/e2e/kustomize/watcher.yaml
Labels: kind/feature, size/L, release-note, lgtm, approved

#780 Change kind Role to ClusterRole for tekton-results-readonly
  docs/api/README.md
Labels: size/XS, release-note-none, ok-to-test, kind/documentation, lgtm, approved
