Repository tektoncd/results, pull requests merged in 2025-05, with the labels that each got.

#1001 [CLI enchancement] Add pr describe command
  docs/cli/tkn-results_pipelinerun.md
  docs/cli/tkn-results_pipelinerun_describe.md
  docs/man/man1/tkn-results-pipelinerun-describe.1
  docs/man/man1/tkn-results-pipelinerun.1
  pkg/cli/client/records/records.go
  pkg/cli/client/records/records_test.go
  pkg/cli/cmd/pipelinerun/describe.go
  pkg/cli/cmd/pipelinerun/describe_test.go
  pkg/cli/cmd/pipelinerun/list.go
  pkg/cli/cmd/pipelinerun/list_test.go
  pkg/cli/cmd/pipelinerun/pipelinerun.go
  pkg/cli/cmd/taskrun/list.go
  pkg/cli/cmd/taskrun/list_test.go
  pkg/cli/cmd/taskrun/logs.go
  pkg/cli/common/constants.go
  pkg/cli/common/resource_types.go
  pkg/cli/options/describe.go
Labels: kind/feature, release-note, size/XL, lgtm, approved

#1004 [CLI enhancement] Add `To be deprecated` message for the older commands
  pkg/cli/cmd/help.txt
  pkg/cli/cmd/root.go
  pkg/cli/dev/cmd/logs/get.go
  pkg/cli/dev/cmd/logs/list.go
  pkg/cli/dev/cmd/logs/logs.go
  pkg/cli/dev/cmd/records/get.go
  pkg/cli/dev/cmd/records/list.go
  pkg/cli/dev/cmd/records/records.go
  pkg/cli/dev/cmd/result/describe.go
  pkg/cli/dev/cmd/result/list.go
  pkg/cli/dev/cmd/result/result.go
  pkg/cli/dev/flags/flags.go
Labels: release-note, kind/misc, size/M, lgtm, approved

#1009 Bump Kind k8s version
  test/e2e/kind-cluster.yaml
Labels: size/XS, release-note, kind/misc, lgtm, approved

#1006 Add ghcr.io migration banner to README.md
  docs/README.md
Labels: size/XS, release-note-none, lgtm, approved

#1011 Add support for fetching logs from Splunk
  docs/logging-support.md
  pkg/api/server/v1alpha2/plugin/plugin_logs.go
  pkg/api/server/v1alpha2/plugin/plugin_logs_test.go
  pkg/apis/v1alpha3/types.go
Labels: size/L, release-note, lgtm, approved

#1013 [CLI enchancement] Add support for yaml and json output for the desc command
  docs/cli/tkn-results_pipelinerun_describe.md
  docs/cli/tkn-results_taskrun_describe.md
  docs/man/man1/tkn-results-pipelinerun-describe.1
  docs/man/man1/tkn-results-taskrun-describe.1
  pkg/cli/cmd/pipelinerun/describe.go
  pkg/cli/cmd/pipelinerun/describe_test.go
  pkg/cli/cmd/taskrun/describe.go
  pkg/cli/cmd/taskrun/describe_test.go
Labels: kind/feature, size/L, release-note, lgtm, approved

#1017 Lower priority of log message
  pkg/watcher/reconciler/dynamic/dynamic.go
Labels: size/XS, release-note, kind/misc, lgtm, approved
