Repository tektoncd/results, pull requests merged in 2025-07, with the labels that each got.

#1051 Fix the flaky unit test in field mask
  internal/fieldmask/fieldmask_test.go
Labels: kind/bug, size/XS, release-note-none, lgtm, approved

#1060 Add anti-affinity rules to results's replicas
  config/base/api.yaml
  config/base/watcher.yaml
Labels: release-note, size/M, lgtm, approved

#1067 feat: enable readOnlyRootFilesystem and add required writable mounts
  config/components/local-db/201-sql-deployment.yaml
Labels: size/S, ok-to-test, release-note, lgtm, approved, kind/security

#1071 Remove duplicate data from dynamic reconciler logging
  pkg/watcher/reconciler/dynamic/dynamic.go
Labels: size/L, release-note, kind/cleanup, lgtm, approved
